### ISSUE TITLE
PE 2017.2.3 - tuning settings are being reapplied every puppet run

### ISSUE THREAD

**Issue by jessereynolds** [npwalker/pe_databases#11]
I've added pe_databases using default settings for tunings and now the changes are being applied afresh every puppet run, causing postgresql to be restarted every puppet run. It seems to be fighting with `puppet_enterprise::profile::database`

What is the recommended classification changes to have this module take over management of the postgresql tuning settings? 

I had to disable managing of the postgresql service so it doesn't conflict with the puppet_enteprise module:

`pe_databases::postgresql_settings::manage_postgresql_service: false`

But i don't think that would be affecting things. 

Eg:
```
Notice: /Stage[main]/Pe_databases::Postgresql_settings/Postgresql_conf[max_connections]/value: value changed '200' to '1000'
...
Notice: /Stage[main]/Puppet_enterprise::Profile::Database/Pe_postgresql::Server::Config_entry[max_connections]/Pe_postgresql_conf[max_connections]/value: value changed '1000' to '200'
```

The config file is left like this:

```
grep max_connections /opt/puppetlabs/server/data/postgresql/9.4/data/postgresql.conf
max_connections = 200 # (change requires restart)
```

**Comment by npwalker** [comment]
@jessereynolds `puppet_enterprise::profile::database` isn't applied on agent runs by default so you must have applied it.  

If that's the case then you probably just don't want to manage the postgresql settings with pe_databases.

**Comment by jessereynolds** [comment]
@npwalker ah ... perhaps adding an HA replica caused the MoM to be classified with puppet_enterprise::profile::database to manage replication configuration. Thanks.

**Comment by npwalker** [comment]
@jessereynolds I'll close this for now.  I went ahead and submitted [an internal ticket and a PR](https://tickets.puppetlabs.com/browse/PE-22295) that would make a node group for `puppet_enterprise::profile::database` so that we're always managing it.  

At this point we are managing database settings because we do it during install /upgrade so not doing it via agent runs seems more confusing to me at this point.
