### ISSUE TITLE
PE 2017.2 doesn't seem to have a fact_values table

### ISSUE THREAD

**Issue by mhjacks** [npwalker/pe_databases#5]
`Error: Error executing SQL; psql returned pid 16127 exit 1: 'ERROR:  relation "fact_values" does not exist
'
Error: /Stage[main]/Pe_databases::Postgresql_settings/Pe_databases::Set_puppetdb_table_autovacuum_cost_delay_zero[fact_values]/Pe_databases::Set_table_attribute[Set autovacuum_cost_delay=0 for fact_values]/Postgresql_psql[Set autovacuum_vacuum_cost_delay=0 for fact_values]/command: change from notrun to ALTER TABLE fact_values SET ( autovacuum_vacuum_cost_delay = 0 ) failed: Error executing SQL; psql returned pid 16127 exit 1: 'ERROR:  relation "fact_values" does not exist
'
`

It's good to see there's a param to turn it off; but maybe it should have some different defaulting behavior now.

**Comment by npwalker** [comment]
Thanks @mhjacks!  Managing fact_values is skipped if on PE 2017.2 or newer.
